### ISSUE TITLE
unable to compile with R version 3.3.3

### ISSUE THREAD

**Issue by lmanchon** [tengfei-emory/QuantNorm#1]
--Hi, 

is there a solution to compile package with R 3.3.3 or i need unfortunately 3.4 ?

thank you --

**Comment by tengfei-emory** [comment]
Thank you for letting me know this. Could you please try again?

**Comment by lmanchon** [comment]
all right now !
** testing if installed package can be loaded
* DONE (QuantNorm)
Thank you so much.
