### ISSUE TITLE
QunatNorm applying a pre-made distance matrix by ngsDist as input?

### ISSUE THREAD

**Issue by yuisato** [tengfei-emory/QuantNorm#2]
Hi! Could QuantNorm be applied to an NxN distance matrix as input, that is already made by another program, specifically ngsDist (https://github.com/fgvieira/ngsDist)?

Seeing that the QuantNorm publication abstract states; "Instead of adjusting the original data matrices, we design an adaptive method to directly adjust the dissimilarity matrix between samples.", I am assuming this is possible...  But at the moment, it looks like QuantNorm only takes a raw N x p data matrix as the input..??

Your help is greatly appreciated!!

**Comment by tengfei-emory** [comment]
Thank you for the questions. The answer is yes! I just modified the package a little bit and it should accept distance matrix input now. 

For example, we can input a Pearson correlation matrix, cor(ENCODE), as following:

`corrected.distance.matrix <- QuantNorm(cor(ENCODE),batches,method='row/column', tol=1e-4)`

Please let me know if there are still problems and I can make further improvements.

**Comment by yuisato** [comment]
Fantastic! Thank you very much.
